/**
 * @file sine_wave.c
 * @brief Example: generate a sine wave and visualise its magnitude spectrum.
 *
 * This program demonstrates MD_sine_wave() by:
 *   1. Generating a 440 Hz sine wave at 44100 Hz sample rate (N=4096 samples).
 *   2. Computing its magnitude spectrum via MD_magnitude_spectrum().
 *   3. Writing the results to CSV and to an interactive HTML visualisation
 *      (Plotly.js, no server required).
 *
 * Build and run (from the repository root):
 *   make                          # build libminidsp.a first
 *   make -C examples plot         # build example, run it, generate HTML
 *   open examples/sine_wave.html  # interactive spectrum plot
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "minidsp.h"
#include "plot_html.h"

/* -----------------------------------------------------------------------
 * Write the interactive HTML visualisation.
 *
 * The HTML file is completely self-contained: spectrum data is embedded
 * as JavaScript arrays, and Plotly.js is loaded from CDN.
 * Just open the file in any modern browser -- no local server needed.
 * -----------------------------------------------------------------------*/
static int write_html(const char *path,
                      const double *freqs, const double *mags,
                      unsigned num_bins,
                      double sample_rate, unsigned N,
                      double freq_hz)
{
    FILE *fp = fopen(path, "w");
    if (!fp) {
        fprintf(stderr, "cannot open %s for writing\n", path);
        return -1;
    }

    char subtitle[256];
    snprintf(subtitle, sizeof(subtitle),
        "%.0f Hz sine wave &nbsp;|&nbsp;\n"
        "    sample rate %.0f Hz &nbsp;|&nbsp;\n"
        "    FFT size %u",
        freq_hz, sample_rate, N);

    plot_html_begin(fp, "Sine Wave Spectrum", subtitle, 0);

    fprintf(fp,
        "  <div id=\"plot\" class=\"plot-container\"></div>\n"
        "  <div class=\"info\">\n"
        "    <strong>What you are seeing:</strong><br>\n"
        "    A pure sine wave at %.0f Hz produces a single spectral spike at that\n"
        "    frequency.  The x-axis shows frequency in Hz (bin index &times;\n"
        "    <code>sample_rate / N</code>).  Hover for exact values.\n"
        "    Use the Plotly toolbar to zoom, pan, or export to PNG/SVG.\n"
        "  </div>\n\n",
        freq_hz);

    /* ---- Embed spectrum data as JS arrays ---- */
    fprintf(fp, "  <script>\n");
    fprintf(fp, "    // Spectrum data generated by sine_wave.c\n");
    plot_html_js_array(fp, "freqs", freqs, num_bins, "%.4f");
    plot_html_js_array(fp, "mags", mags, num_bins, "%.8f");
    fprintf(fp, "\n");

    /* ---- Plotly visualisation ---- */
    fprintf(fp,
        "    const maxMag = Math.max(...mags);\n"
        "    const peakIdx = mags.indexOf(maxMag);\n"
        "    const annotations = [{\n"
        "      x: freqs[peakIdx], y: maxMag,\n"
        "      text: '%.0f Hz',\n"
        "      showarrow: true, arrowhead: 2,\n"
        "      ax: 50, ay: -35,\n"
        "      font: { size: 13 }\n"
        "    }];\n"
        "\n"
        "    Plotly.newPlot('plot', [{\n"
        "      x: freqs, y: mags,\n"
        "      type: 'scatter', mode: 'lines',\n"
        "      line: { color: '#2563eb', width: 1.2 },\n"
        "      name: 'Amplitude',\n"
        "      hovertemplate: '%%{x:.1f} Hz<br>Amplitude: %%{y:.6f}<extra></extra>'\n"
        "    }], {\n"
        "      title: { text: 'Magnitude Spectrum of a %.0f Hz Sine Wave', font: { size: 15 } },\n"
        "      xaxis: { title: 'Frequency (Hz)', range: [0, %.1f] },\n"
        "      yaxis: { title: 'Amplitude', range: [0, maxMag * 1.15] },\n"
        "      annotations: annotations,\n"
        "      margin: { t: 55, r: 30, b: 55, l: 65 },\n"
        "      height: 380\n"
        "    }, { responsive: true });\n"
        "  </script>\n",
        freq_hz, freq_hz, sample_rate / 2.0);

    plot_html_end(fp);
    fclose(fp);
    return 0;
}

int main(void)
{
    /* ------------------------------------------------------------------
     * Signal parameters
     * ----------------------------------------------------------------*/
    const unsigned N           = 4096;       /* FFT size (samples)    */
    const double   sample_rate = 44100.0;    /* Hz                    */
    const double   freq_hz     = 440.0;      /* A4 concert pitch      */
    const double   amplitude   = 1.0;
    const unsigned num_bins    = N / 2 + 1;

    /* ------------------------------------------------------------------
     * Generate the sine wave using MD_sine_wave
     * ----------------------------------------------------------------*/
    double *signal = malloc(N * sizeof(double));
    double *mag    = malloc(num_bins * sizeof(double));
    double *freqs  = malloc(num_bins * sizeof(double));

    if (!signal || !mag || !freqs) {
        fprintf(stderr, "allocation failed\n");
        return 1;
    }

    //! [generate-signal]
    MD_sine_wave(signal, N, amplitude, freq_hz, sample_rate);
    //! [generate-signal]

    /* ------------------------------------------------------------------
     * Compute the magnitude spectrum
     * ----------------------------------------------------------------*/
    MD_magnitude_spectrum(signal, N, mag);

    /* Convert to single-sided amplitude spectrum */
    for (unsigned k = 0; k < num_bins; k++) {
        freqs[k] = (double)k * sample_rate / (double)N;
        mag[k] /= (double)N;
        if (k > 0 && k < N / 2)
            mag[k] *= 2.0;
    }

    /* ------------------------------------------------------------------
     * Write results to CSV
     * ----------------------------------------------------------------*/
    const char *csv_file = "sine_wave.csv";
    FILE *fp = fopen(csv_file, "w");
    if (!fp) {
        fprintf(stderr, "cannot open %s for writing\n", csv_file);
        return 1;
    }

    fprintf(fp, "bin,frequency_hz,magnitude\n");
    for (unsigned k = 0; k < num_bins; k++)
        fprintf(fp, "%u,%.4f,%.8f\n", k, freqs[k], mag[k]);
    fclose(fp);

    printf("Wrote %u frequency bins to %s\n", num_bins, csv_file);

    /* ------------------------------------------------------------------
     * Write interactive HTML visualisation
     * ----------------------------------------------------------------*/
    const char *html_file = "sine_wave.html";
    if (write_html(html_file, freqs, mag, num_bins,
                   sample_rate, N, freq_hz) == 0) {
        printf("Wrote interactive plot to %s\n", html_file);
    }

    printf("Signal: %.0f Hz sine wave, amplitude %.1f\n", freq_hz, amplitude);
    printf("Sample rate: %.0f Hz, FFT size: %u\n", sample_rate, N);

    /* ------------------------------------------------------------------
     * Cleanup
     * ----------------------------------------------------------------*/
    free(freqs);
    free(mag);
    free(signal);
    MD_shutdown();

    return 0;
}
